# Generated by Django 3.2 on 2022-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0004_alter_quest_author'),
        ('accounts', '0002_auto_20220205_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_quests',
            field=models.ManyToManyField(to='latte.Quest'),
        ),
    ]
