# Generated by Django 3.2 on 2022-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_my_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_quests_count',
            field=models.IntegerField(default=0),
        ),
    ]
