# Generated by Django 3.2 on 2022-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0005_alter_quest_author'),
        ('accounts', '0004_profile_my_quests_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_quests',
            field=models.ManyToManyField(related_name='my_quests_set', to='latte.Quest'),
        ),
    ]
