# Generated by Django 3.2 on 2022-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0005_alter_quest_author'),
        ('accounts', '0006_alter_profile_my_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_quests',
            field=models.ManyToManyField(related_name='quests', to='latte.Quest'),
        ),
    ]
