# Generated by Django 3.2 on 2022-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0005_alter_quest_author'),
        ('accounts', '0007_alter_profile_my_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='done_quests',
            field=models.ManyToManyField(related_name='done_quests', to='latte.Quest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='done_quests_count',
            field=models.IntegerField(default=0),
        ),
    ]
