# Generated by Django 3.2 on 2022-02-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('latte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='quest',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='quest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='latte.category'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='latte.school'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latte.quest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latte.quest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='done_users',
            field=models.ManyToManyField(blank=True, related_name='done_user', through='latte.Done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_user', through='latte.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
