# Generated by Django 3.2 on 2022-01-20 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('latte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latte.quest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='done_user',
            field=models.ManyToManyField(blank=True, related_name='done_user', through='latte.Done', to=settings.AUTH_USER_MODEL),
        ),
    ]
