# Generated by Django 3.2 on 2022-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0002_auto_20220120_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='done_count',
            field=models.IntegerField(default=0),
        ),
    ]
