# Generated by Django 3.2 on 2022-01-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0003_quest_done_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='done_user',
            new_name='done_users',
        ),
    ]
