# Generated by Django 3.2 on 2022-01-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0004_rename_done_user_quest_done_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
