# Generated by Django 3.2 on 2022-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0005_quest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='quest_count',
            field=models.IntegerField(default=0),
        ),
    ]
