# Generated by Django 3.2 on 2022-01-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0006_school_quest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='quest_count',
            field=models.IntegerField(default=0),
        ),
    ]
